import { ArrowRight, ArrowUpRight, Check } from 'lucide-react'
import { catalog, formatPrice } from '../content/site'
import { Breadcrumbs, PageCTA, PageIntro } from '../components/pages/PageParts'

export default function PricesPage({ onOrder }) {
  return <><Breadcrumbs items={[{ label: 'Стоимость' }]} /><PageIntro eyebrow="БЕЗ НЕОЖИДАННОСТЕЙ" title={<>Сначала — задача.<br /><em>Потом — точная цена.</em></>} description="Здесь — начальная стоимость. Итоговую сумму и срок согласуем после просмотра задания, до начала работы." />
    <div className="pricing-layout"><section className="price-list" aria-label="Начальная стоимость работ">{catalog.map(service => <div className="price-row" key={service.slug}><a href={service.path}>{service.label}<ArrowUpRight size={15} /></a><strong>от {formatPrice(service.price)} ₽</strong><button type="button" onClick={() => onOrder(service.label)} aria-label={`Узнать стоимость: ${service.label}`}><ArrowRight size={20} /></button></div>)}</section>
      <aside className="price-explanation"><span className="support-eyebrow">КАК СЧИТАЕМ</span><h2>Стоимость под вашу работу</h2><ol><li><strong>Объём и сложность</strong><span>Количество разделов, расчёты, графика и специальные программы.</span></li><li><strong>Требования</strong><span>Методичка, оформление и исходные данные.</span></li><li><strong>Срок</strong><span>Точная дата готовности и промежуточные проверки.</span></li></ol><a className="text-action" href="/guides/ot-chego-zavisit-cena/">Разобраться подробнее <ArrowUpRight size={16} /></a></aside></div>
    <section className="subscription-note"><div><span className="support-eyebrow">ЕСЛИ ЗАДАНИЙ НЕСКОЛЬКО</span><h2>Подписка студенту</h2><p>Помощь в течение месяца, приоритетная связь с менеджером и поддержка по замечаниям преподавателя. Состав заданий и условия обсудим заранее.</p></div><div><strong>2 490 ₽<small>/ месяц</small></strong><button type="button" className="text-action" onClick={() => onOrder('Подписка студенту')}>Обсудить подписку <ArrowRight size={17} /></button></div></section>
    <div className="payment-note"><Check size={24} /><p><strong>Порядок оплаты согласуем в переписке.</strong> Можно договориться о предоплате или этапах. Правки по исходному заданию уже входят в стоимость.</p><a href="/guarantees/">Условия работы <ArrowUpRight size={16} /></a></div><PageCTA onOrder={onOrder} title="Узнаем стоимость вашей работы?" /></>
}
