import { siteUrl } from '../lib/siteUrl.js'
import { ArrowRight, ArrowUpRight, Check } from 'lucide-react'
import { catalog, formatPrice } from '../content/site'
import { Breadcrumbs, DocumentArt, PageCTA, PageIntro } from '../components/pages/PageParts'

export default function ServicesPage({ onOrder }) {
  return <><Breadcrumbs items={[{ label: 'Услуги' }]} /><div className="page-hero-split"><PageIntro eyebrow="УСЛУГИ" title={<>Помощь с<br /><em>учебными работами</em></>} description="Отправьте задание и требования преподавателя — мы быстро оценим работу и заранее сообщим срок и стоимость."><div className="page-inline-facts"><a href="#service-prices">Услуги и начальные цены <ArrowRight size={16} /></a></div></PageIntro><DocumentArt /></div>
    <section id="service-prices" className="catalog-list" aria-label="Все направления помощи">{catalog.map((service, index) => <a className="catalog-row" href={siteUrl(service.path)} key={service.slug}><span className="catalog-number">0{index + 1}</span><img src={siteUrl(`/assets/services/${service.icon}.svg`)} alt="" width="62" height="62" /><div><h2>{service.label}</h2><p>{service.lead}</p></div><span className="catalog-price">от {formatPrice(service.price)} ₽</span><span className="round-link"><ArrowUpRight size={20} /></span></a>)}</section>
    <section className="service-terms" aria-label="Стоимость и оплата">
      <div className="price-explanation"><span className="support-eyebrow">РАСЧЁТ СТОИМОСТИ</span><h2>От чего зависит цена</h2><ol><li><strong>Объём и сложность</strong><span>Количество разделов, расчёты, графика и специальные программы.</span></li><li><strong>Требования</strong><span>Методичка, оформление и исходные данные.</span></li><li><strong>Срок</strong><span>Дата готовности и промежуточные проверки.</span></li></ol><a className="text-action" href={siteUrl('/guides/ot-chego-zavisit-cena/')}>Подробнее о расчёте цены <ArrowUpRight size={16} /></a></div>
      <div className="service-payment"><span className="support-eyebrow">ПОРЯДОК ОПЛАТЫ</span><strong className="service-payment-amount">25%<span>обычная предоплата</span></strong><h2>Сначала проверяете —<br />потом оплачиваете остаток</h2><p>Готовую работу отправляем для просмотра в PDF с водяным знаком. Если есть замечания по заданию, вносим исправления. После вашей проверки и окончательной оплаты передаём работу без водяных знаков и все исходные файлы.</p><p className="service-payment-note"><Check size={18} />Условия и срок согласуем до начала работы.</p><a className="text-action" href={siteUrl('/guarantees/')}>Гарантии и доработки <ArrowUpRight size={16} /></a></div>
    </section>
    <div className="page-note"><span>Нужно комплексное задание?</span><p>Курсовая может включать расчёты, чертежи и презентацию. Оценим все части вместе и заранее сообщим итоговую стоимость.</p><button className="text-action" type="button" onClick={() => onOrder()}>Оценить задание <ArrowRight size={17} /></button></div><PageCTA onOrder={onOrder} /></>
}
